moving to the new branch
mohamedSabry0/smashing-magazine-clone pull request #1
Opened 2019-11-22 17:58 UTC by mohamedSabry0

2019-11-29 22:02 UTC, pelzolga123 commented on index.html
> +			<figure id="smash-subscribers">
It should be an article

2019-11-29 22:02 UTC, pelzolga123 commented on index.html
> +			<figure class="smashing-tv">
It should be an article

2019-11-29 22:02 UTC, pelzolga123 commented on index.html
> +		<section class="book-ad-2">
It should be an article

2019-11-29 22:02 UTC, pelzolga123 commented on index.html
> +			<figure>
It should be an article.

2019-11-29 22:03 UTC, pelzolga123 requested changes
Project looks great but needs some changes in navbar and  main content.

2019-11-29 22:04 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Your project looks :+1: amazing! But there are a few things to change.

##### Navigation bar

* [ ] Project should use `div` and position elements as at the source page. That means, you need to look how it's done on original website and add all missing elements inside your navbar `li` elements (content is not important). The same with `div` element, it should contain `nav` like original website.  
[link to page](https://www.smashingmagazine.com/)

##### 1 article row

* [ ] It should contain 1 article, which takes full width. See comments above, I pointed, where you need to have articles.

* This part is a little messed up, please make `h1` and `button`  display properly. 

![image](https://user-images.githubusercontent.com/20416431/69891174-43b53480-1303-11ea-96b8-dbd012c39f29.png)

### Please kindly Fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack. *Happy coding*

2019-12-02 18:13 UTC, MauricioRobayo approved these changes
Great job fixing the previous requirements 👍 , and very well done overall, the project looks great.

Keep up the good work 😄 .

**Status**: Approve. 
🚀

2019-12-02 19:22 UTC, merged

2019-12-02 19:22 UTC, RodolfoRodriguezMata commented
Thanks for all your feedback! :)